### PR TITLE
LeetCode Solutions

### PR DESCRIPTION
**Pull request by thecoder8890**
Problems that cover :-

[problem 1](https://leetcode.com/problems/longest-substring-without-repeating-characters/)
[problem 2 ](https://leetcode.com/problems/add-two-numbers/)
[problem 3](https://leetcode.com/problems/two-sum/)

Can you please check : @AkashSingh3031

### CODE REVIEW

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Create folder `Problems` and add solution code in a folder
like  `_0002)_Add_Two_Numbers.java`  instead of  `Java/Easy/AddTwoNumbers.java `

**Comment by thecoder8890** [comment]
Ok sure will do that and again raise a PR

**Comment by thecoder8890** [comment]
@AkashSingh3031 Changes done

**Review by AkashSingh3031 — COMMENTED** [review]
Accepted

**Pull request merged**
