### PR TITLE
Added Some Algorithms for Java

### PR DESCRIPTION
**Pull request by sayeedajmal**
I am working for Algorithms For Java.I will Try My best..

### CODE REVIEW

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Please Add the searching algorithm program in the `Searching` folder and the sorting algorithm program in the `Sorting` folder

**Comment by sayeedajmal** [comment]
> Please Add the searching algorithm program in the `Searching` folder and the sorting algorithm program in the `Sorting` folder

Sir, I already Added Program in Correct Folder....

**Review by AkashSingh3031 — COMMENTED** [review]
Accepted

**Comment by AkashSingh3031** [comment]
> > Please Add the searching algorithm program in the `Searching` folder and the sorting algorithm program in the `Sorting` folder
> 
> Sir, I already Added the Program in the Correct Folder....

ok

**Pull request merged**
