### PR TITLE
Create Stacks.java

### PR DESCRIPTION
**Pull request by nisabmohd**

### CODE REVIEW

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Check code again
Not working the main function

**Comment by nisabmohd** [comment]
> Check code again Not working the main function

image

**Comment by nisabmohd** [comment]
> > > Check the code again Not working the main function
> > 
> > 
> > image
> 
> Check online compiler image
> 
> maybe some regions do not read file in online compiler

Rename the file only to Stacks.java
The T is for Generic , like The stack can be of any data type

**Comment by AkashSingh3031** [comment]
Add a snapshot of the running code when you send pull-request
Then easy to check the correct code 

`I already mention adding a snapshot of the running code in the code of conduct`

**Comment by nisabmohd** [comment]
> Add a snapshot of the running code when you send pull-request Then easy to check the correct code
> 
> `I already mention adding a snapshot of the running code in the code of conduct`

sure

**Review by AkashSingh3031 — APPROVED** [review]

**Pull request merged**
