### PR TITLE
Textogram

### PR DESCRIPTION
**Pull request by poojitha2002**
# Have you read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md)?
- YES 

## Project URL
-  https://poojitha2002.github.io/Textogram/

## Category
- 𝑷𝒓𝒐𝒋𝒆𝒄𝒕𝒔 

## Changes
- Add a new web project - Textogram

## **Screenshots** 
- image

## Checklist
- [x] I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md)- yes
- [x] I've checked the issue list before deciding what to submit.- yes
- [x] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).-yes
- [x] I've add work in proper folder- yes
- [x] I've not delete/modify previous codes- yes

### CODE REVIEW

**Review by AkashSingh3031 — COMMENTED** [review]
Accepted

**Comment by poojitha2002** [comment]
Thank you!

**Comment by poojitha2002** [comment]
Bhaiya will you merge?

**Comment by AkashSingh3031** [comment]
> Bhaiya will you merge?

Yes, I will merge this, 
I checked warning of this code
image
image

**Pull request merged**
