### PR TITLE
Revert "Added ML Project"

### PR DESCRIPTION
**Pull request by AkashSingh3031**
Reverts AkashSingh3031/The-Complete-FAANG-Preparation#18

### CODE REVIEW

**Review by AkashSingh3031 — COMMENTED** [review]
Please check your file

**Comment by AkashSingh3031** [comment]
@onlykingKD, please check your file 
It is not open
You follow the contributing rule [https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#contributing-](url)

**Comment by onlykingKD** [comment]
> @onlykingKD, please check your file
> It is not open
> You follow the contributing rule [https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#contributing-](url)

My file is not open. What does that mean ? Can you please elaborate ?
Thank you.

**Comment by AkashSingh3031** [comment]
@onlykingKD  you push the only file 
image

After merging the file then not open like lock file

**Pull request closed without merging**
