### PR TITLE
Buy and sell stock

### PR DESCRIPTION
**Pull request by IjayAbby**
# Have you read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md)?
- [X] YES
- [ ] NO

## Category
- [ ] 𝑴𝒊𝒔𝒄𝒆𝒍𝒍𝒂𝒏𝒆𝒐𝒖𝒔 𝑺𝒕𝒖𝒇𝒇.
- [X] 𝑫𝑺𝑨 + CP
- [ ] 𝑻𝒆𝒄𝒉𝒏𝒊𝒄𝒂𝒍 𝑺𝒖𝒃𝒋𝒆𝒄𝒕
- [ ] 𝑳𝒐𝒘 𝑳𝒆𝒗𝒆𝒍 𝑫𝒆𝒔𝒊𝒈𝒏
- [ ] 𝑷𝒓𝒐𝒋𝒆𝒄𝒕𝒔
- [ ] 𝑰𝒎𝒑𝒐𝒓𝒕𝒂𝒏𝒕 𝑩𝒐𝒐𝒌𝒔 𝒂𝒏𝒅 𝑹𝒆𝒔𝒐𝒖𝒓𝒄𝒆𝒔
- [ ] 𝑩𝒆𝒉𝒂𝒗𝒊𝒐𝒖𝒓𝒂𝒍 𝑰𝒏𝒕𝒆𝒓𝒗𝒊𝒆𝒘 𝑸𝒖𝒆𝒔𝒕𝒊𝒐𝒏𝒔

## Changes
- Add Buy and sell stock code.

## Checklist ✅
- [X] I've read the instructions on the README file before submitting my application.
- [X] I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- [X] I've checked the issue list before deciding what to submit.
- [X] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [X] I've add work in proper folder
- [X] I've not delete/modify previous codes.

### CODE REVIEW

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Add full code with `print output` in the console

and also change the numbering
if add same problem with different approaches then numbering like

`_021_i_)_Max_Profit.js`
`_021_ii_)_Max_Profit.js`

and different problems then change the number like `21` & `22`

**Comment by IjayAbby** [comment]
I had an issue with the spelling mistake of the previous solutions it is supposed to be Buy and Sell not Shell.
Should I fix the spelling on the other files?

**Comment by AkashSingh3031** [comment]
> I had an issue with the spelling mistake of the previous solutions it is supposed to be Buy and Sell not Shell. Should I fix the spelling on the other files?

Yes, fix the name and if the problem name same but the solution is a different approach then name like `_1_i)` & `1_ii)` 
As mentioned above comment

**Comment by IjayAbby** [comment]
Hello, is everything to your expectations?

**Review by AkashSingh3031 — APPROVED** [review]

**Pull request merged**
