### PR TITLE
Added Weather App Java Android app

### PR DESCRIPTION
**Pull request by SuriyaaVijay**
Can you please assign me under hacktoberfest-accepted label ! Pleaseee !!

Added Android Studio based Java Mobile App with all the files

# Have you read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md)?
- [x] YES
- [ ] NO

## Screenshots
SS1 | SS2 
:------------------:|:-------------------:
image | image

## What is the current behavior?
- Issue Number: #279 

## Category
- [ ] 𝑴𝒊𝒔𝒄𝒆𝒍𝒍𝒂𝒏𝒆𝒐𝒖𝒔 𝑺𝒕𝒖𝒇𝒇.
- [ ] 𝑫𝑺𝑨 + CP
- [ ] 𝑻𝒆𝒄𝒉𝒏𝒊𝒄𝒂𝒍 𝑺𝒖𝒃𝒋𝒆𝒄𝒕
- [ ] 𝑳𝒐𝒘 𝑳𝒆𝒗𝒆𝒍 𝑫𝒆𝒔𝒊𝒈𝒏
- [x] 𝑷𝒓𝒐𝒋𝒆𝒄𝒕𝒔
- [ ] 𝑰𝒎𝒑𝒐𝒓𝒕𝒂𝒏𝒕 𝑩𝒐𝒐𝒌𝒔 𝒂𝒏𝒅 𝑹𝒆𝒔𝒐𝒖𝒓𝒄𝒆𝒔
- [ ] 𝑩𝒆𝒉𝒂𝒗𝒊𝒐𝒖𝒓𝒂𝒍 𝑰𝒏𝒕𝒆𝒓𝒗𝒊𝒆𝒘 𝑸𝒖𝒆𝒔𝒕𝒊𝒐𝒏𝒔

## Changes
-Added Android Studio based Java Mobile App with all the files
- created a new folder for java mobile apps

## Checklist ✅
- [x] I've read the instructions on the README file before submitting my application.
- [x] I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- [x] I've checked the issue list before deciding what to submit.
- [x] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [x] I've add work in proper folder
- [x] I've not delete/modify previous codes.

### CODE REVIEW

**Comment by AkashSingh3031** [comment]
Add a Screenshot of your live project

**Comment by SuriyaaVijay** [comment]
Added bro.
Can you please add the hacktoberfest-accepted label

**Comment by AkashSingh3031** [comment]
@SuriyaaVijay if possible add a live demo of your project in `Readme.md` file in the same project file

**Comment by SuriyaaVijay** [comment]
yes bro will add when I record it. Thank youu

**Pull request merged**
