### PR TITLE
Added Interview Bit Arrays and Trees

### PR DESCRIPTION
**Pull request by sainikhil1605**
Please go through the added interview bit files I added

### CODE REVIEW

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Please add the problem in the folder
like `/Arrays/Bucketing/Python/FindDuplicateInArray.py`

if you solve the problem in python then put it into the python folder and if in java then java folder

**Comment by AkashSingh3031** [comment]
@sainikhil1605 
Also, add Programming folder then create Array folder so..on

**Comment by sainikhil1605** [comment]
I have the mentioned changes

**Review by AkashSingh3031 — COMMENTED** [review]
Accepted

**Pull request merged**
