### PR TITLE
Added Binary Search Tree

### PR DESCRIPTION
**Pull request by codeaholic-shub**
Hello @AkashSingh3031 ,
As u have said to remove .exe file,
I have done it ,
Kindly Have a Look !

### CODE REVIEW

**Comment by AkashSingh3031** [comment]
@codeaholic-shub 
Numbering the question like `_01) _<code name>.cpp`

**Comment by codeaholic-shub** [comment]
> @codeaholic-shub
> Numbering the question like `_01) _<code name>.cpp`

Done @AkashSingh3031 ,
According to yours instructions and guidelines !

**Comment by AkashSingh3031** [comment]
@codeaholic-shub 
Check numbering 1st & 2nd question 
Do with all questions

Because, if you write `1, 2 ... 10, 11` then after merge the code

It looks like `1, 10, 11, .. 2, 3 ..9`
So, I write `01, 02...`

**Comment by amandewatnitrr** [comment]
Hello @codeaholic-shub ,
Hope you are doing well?? I am also a contributor to these repository and would like to mention that kindly follow the instructions to contribute, although there's no problem, but you have made direct commit to the master branch. It's mentioned in the "readme.md" that a seprate branch needs to be made and the changes must be commited in that branch. 

Please take it into consideration, next time when you make a commit. Hope you have a nice day.

May the Open-Source, be with you!!!

**Review by AkashSingh3031 — COMMENTED** [review]
Accepted

**Pull request merged**
