### PR TITLE
Add Python And Javascript Based Projects

### PR DESCRIPTION
**Pull request by Akashkhandelwal191**
# Have you read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md)?
- [x] YES
- [ ] NO

## Project URL
- 

## What is the current behavior?
- Issue Number: #...

## Category
- [ ] 𝑨𝑺𝑲 𝒀𝒐𝒖𝒓 𝑫𝒐𝒖𝒃𝒕𝒔
- [ ] 𝑴𝒊𝒔𝒄𝒆𝒍𝒍𝒂𝒏𝒆𝒐𝒖𝒔 𝑺𝒕𝒖𝒇𝒇.
- [ ] 𝑫𝑺𝑨
- [ ] 𝑪𝒐𝒎𝒑𝒆𝒕𝒊𝒕𝒊𝒗𝒆 𝑷𝒓𝒐𝒈𝒓𝒂𝒎𝒎𝒊𝒏𝒈
- [ ] 𝑻𝒆𝒄𝒉𝒏𝒊𝒄𝒂𝒍 𝑺𝒖𝒃𝒋𝒆𝒄𝒕
- [ ] 𝑳𝒐𝒘 𝑳𝒆𝒗𝒆𝒍 𝑫𝒆𝒔𝒊𝒈𝒏
- [x] 𝑷𝒓𝒐𝒋𝒆𝒄𝒕𝒔
- [ ] 𝑰𝒎𝒑𝒐𝒓𝒕𝒂𝒏𝒕 𝑩𝒐𝒐𝒌𝒔 𝒂𝒏𝒅 𝑹𝒆𝒔𝒐𝒖𝒓𝒄𝒆𝒔
- [ ] 𝑩𝒆𝒉𝒂𝒗𝒊𝒐𝒖𝒓𝒂𝒍 𝑰𝒏𝒕𝒆𝒓𝒗𝒊𝒆𝒘 𝑸𝒖𝒆𝒔𝒕𝒊𝒐𝒏𝒔

## Changes
- Description of changes

## **Screenshots** 
- (Add Runnig Work Demo Image)

## Checklist
- [x] I've read the [Contributing Guidelines](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/CONTRIBUTING.md).
- [x] I've checked the issue list before deciding what to submit.
- [x] I've follow [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index).
- [x] I've add work in proper folder
- [x] I've not delete/modify previous codes.

### CODE REVIEW

**Comment by Akashkhandelwal191** [comment]
Add Python And Javascript Based Projects

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Add demo video or Screenshot of both project

**Comment by Akashkhandelwal191** [comment]
> Add demo video or Screenshot of both project
> Change name `Python Based Project` to `Desktop Development`

Ok

**Comment by Akashkhandelwal191** [comment]
I have Added Demo Video And ScreenShot Of Both the Projects.
And Also Changed Named "Python Based Project" to "Desktop Development"
Approve it

**Review by AkashSingh3031 — COMMENTED** [review]
Accepted

**Pull request merged**
