### PR TITLE
Divide & Conquer Technique For Java

### PR DESCRIPTION
**Pull request by sayeedajmal**
Let's Checkout... @AkashSingh3031

### CODE REVIEW

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Add this file to the `Resources` folder

Try to create an interactive look.
like

use for 1st Heading `<h1></h1>` or `#` and so on

**Comment by sayeedajmal** [comment]
> Add this file to the `Resources` folder
> 
> Try to create an interactive look.
> like
> 
> use for 1st Heading `<h1></h1>` or `#` and so on
# It's All about
Screenshot_2021-06-27_16_20_17
Screenshot_2021-06-27_16_20_19

**Comment by AkashSingh3031** [comment]
@sayeedajmal 
Add your explanation work to [this ](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/1%5D.%20DSA/2%5D.%20Algorithms/02%5D.%20Sorting%20Algorithms/Sorting_Algorithm_Explainations.md)file

**Comment by sayeedajmal** [comment]
> Add this file to the `Resources` folder
> 
> Try to create an interactive look.
> like
> 
> use for 1st Heading `<h1></h1>` or `#` and so on

    Sorry @AkashSingh3031 ..Can you give any sample....!

**Comment by sayeedajmal** [comment]
> @sayeedajmal 
> Add your explanation work to [this ](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/1%5D.%20DSA/2%5D.%20Algorithms/02%5D.%20Sorting%20Algorithms/Sorting_Algorithm_Explainations.md)file

Sorry Sir @AkashSingh3031 .. Can you give any Sample..

**Comment by AkashSingh3031** [comment]
Write all explanation in summary
Like

```
<details>
    <summary> Merge Sort </summary>

       .....Your Merge Sort Explanation..... 
</details>
```

I created summary, only add explanation of merge sort under summary tag

**Comment by sayeedajmal** [comment]
> Write all explanation in summary
> Like
> 
> ```
> <details>
>     <summary> Merge Sort </summary>
> 
>        .....Your Merge Sort Explanation..... 
> </details>
> ```
> 
> I created summary, only add explanation of merge sort under summary tag
> 
> Open link and add...

can i add link of mergesort algorithm of Divide and Conquer technique..?

**Comment by sayeedajmal** [comment]
> Write all explanation in summary
> Like
> 
> ```
> <details>
>     <summary> Merge Sort </summary>
> 
>        .....Your Merge Sort Explanation..... 
> </details>
> ```
> 
> I created summary, only add explanation of merge sort under summary tag
> 
> Open link and add...

# I done It...
## Added Copying Array 
Screenshot_2021-06-27_21_28_22

**Review by AkashSingh3031 — COMMENTED** [review]
Accepted

**Pull request merged**
