### PR TITLE
Added Array Operations For java

### PR DESCRIPTION
**Pull request by sayeedajmal**

### CODE REVIEW

**Comment by amandewatnitrr** [comment]
Hello Sayed,
Hope you are doing well. I am a contributor to this repository and would like to mention kindly follow the instructions to contribute, although there's no problem, but you have made direct commit to the master branch. It's mentioned in the "readme.md" that a seprate branch needs to be made and the changes must be commited in that branch. 

Please take it into consideration, next time when you make a commit. Hope you have a nice day.

May the Open-Source, be with you!!!

**Comment by sayeedajmal** [comment]
> Hello Sayed,
> Hope you are doing well. I am a contributor to this repository and would like to mention kindly follow the instructions to contribute, although there's no problem, but you have made direct commit to the master branch. It's mentioned in the "readme.md" that a seprate branch needs to be made and the changes must be commited in that branch. 
> 
> Please take it into consideration, next time when you make a commit. Hope you have a nice day.
> 
> May the Open-Source, be with you!!!

>  @amandewatnitrr Sir.. Thank you.. So Much.. I just Readout...
> I apologize... But I am New in Learning Github..... That's why I make mistakes....
> Sir, I already Forked The branch....How can I create a new Branch... I already Committed Many changes... If I will create new Branch, then what will with my previous Committed..

**Comment by amandewatnitrr** [comment]
Follow this tutorial by Telusko: https://www.youtube.com/watch?v=OVQK2zzb6U8

- On Gihtub, go to your fork of this repository and on the upper left hand side you cn see master written over button.
- Click on it the  dropdown menu opens.
- Type the name of your branch
- Option appears saying "Create branch <--the_name_you_typed-->"
- Click on that option and the new branch is created.

**Comment by sayeedajmal** [comment]
Thankyou @amandewatnitrr

**Comment by AkashSingh3031** [comment]
@sayeedajmal 
Don't change the `Readme.md` file

Because Contributor profile in order wise
if any new contributor, contribute then those profiles fit in last

So, remove changes of `Readme.md` file

**Comment by sayeedajmal** [comment]
🤭. @AkashSingh3031 I changed it in My Fork...
Okey...Here's synchronized

**Review by AkashSingh3031 — COMMENTED** [review]
Accepted

**Pull request merged**
