### PR TITLE
added practice questions solution from hackerearth

### PR DESCRIPTION
**Pull request by geek-2002**

### CODE REVIEW

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Please follow the [Tree of Index](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation#tree-of-index) for folder creation

And Also mention the question number like `_01)_countdigit.cpp`
if you solved 5th number question then mention `_05)_<problem name>.cpp`

**Comment by geek-2002** [comment]
ok i will mention them

**Comment by AkashSingh3031** [comment]
@geek-2002 
Create folders like `Practice/1]. Basic Programming/1]. Basics of Input-Output/_01)_Maximum_borders.cpp`
Then, again send a pull request

**Comment by amandewatnitrr** [comment]
Hello @geek-2002 ,
Hope you are doing well?? I am also a contributor to these repository and would like to mention that kindly follow the instructions to contribute, although there's no problem, but you have made direct commit to the master branch. It's mentioned in the "readme.md" that a seprate branch needs to be made and the changes must be commited in that branch. 

Please take it into consideration, next time when you make a commit. Hope you have a nice day.

May the Open-Source, be with you!!!

**Pull request closed without merging**
