### PR TITLE
Solution of hackerrank Introduction 

### PR DESCRIPTION
**Pull request by thecoder8890**
Welcome to Java!--------> WelcomeToJava.java 
Java Stdin and Stdout I--------> JavaStdinAndStdoutI.java 
Java If-Else--------> JavaIfElse.java 
Java Stdin and Stdout II--------> JavaStdinAndStdoutII.java 
Java Output Formatting--------> JavaOutputFormatting.java 
Java Loops I--------> JavaLoopsI.java 
Java Loops II--------> JavaLoopsII.java 
Java Datatypes--------> JavaDatatypes.java 
Java End-of-file--------> JavaEndOfFile.java 
Java Static Initializer Block--------> JavaStaticInitializerBlock.java 
Java Int to String--------> JavaIntToString.java 
Java Date and Time--------> JavaDateAndTime.java 
Java Currency Formatter--------> JavaCurrencyFormatter.java

### CODE REVIEW

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Please comment on 1st line of code 
```suggestion
package com.javaaid.hackerrank.solutions.languages.java.introduction;
```

**Comment by AkashSingh3031** [comment]
@thecoder8890  after comment 1st line of code
```suggestion
package com.javaaid.hackerrank.solutions.languages.java.introduction;
```

Then again send a pull request

**Comment by thecoder8890** [comment]
done

**Review by AkashSingh3031 — COMMENTED** [review]
Accepted

**Pull request merged**
