### PR TITLE
Added Selection Sort and Bubble Sort with Explanation...

### PR DESCRIPTION
**Pull request by sayeedajmal**
# Please Review It..!
Screenshot_2021-07-01_01_02_55
Screenshot_2021-07-01_01_03_21

### CODE REVIEW

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Add searching algo explanation in [Searchin_Algorithm_Explanation.md](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/1%5D.%20DSA/2%5D.%20Algorithms/01%5D.%20Searching%20Algorithms/Searching_Algorithms_Explanations.md) file & sorting file in [Sorting_Algorithms_Explation.md](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/1%5D.%20DSA/2%5D.%20Algorithms/02%5D.%20Sorting%20Algorithms/Sorting_Algorithm_Explainations.md)

Don't put the same file every place

like you add `BinarySearch.md ` file in 3 place
Put only ones

**Comment by sayeedajmal** [comment]
# Fixed File Locations.
- Searching Algorithm `searching_algorithm_explanation.md`
- Sorting Algorithm `Sorting_algorithm_explanation.md`
- Brute Force and Exhaustive `BruteForce_Exhaustive.md---`
Screenshot_2021-07-02_14_29_08
# I hope I Done it..!😅

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
image

Put searching algo in [this ](https://github.com/AkashSingh3031/The-Complete-FAANG-Preparation/blob/master/1%5D.%20DSA/2%5D.%20Algorithms/01%5D.%20Searching%20Algorithms/Searching_Algorithms_Explanations.md) file, not in `java` folder

And also put `BrutForce folder` put in `searching  folder`, because the same question in Bruteforce folder

You put same thing in multiple file 
So, put only one
see...
image

**Comment by sayeedajmal** [comment]
# Like This...?
Screenshot_2021-07-02_23_41_50

**Comment by AkashSingh3031** [comment]
Yes, put searching algorithm explanation in searching file & sorting algorithm explanation in sorting file

**Comment by sayeedajmal** [comment]
> Yes, put searching algorithm explanation in searching file & sorting algorithm explanation in sorting file

Done!

**Comment by AkashSingh3031** [comment]
I added this part in `sorting.md file`
image

so close this pull request
Because of conflicting files
image

you can send a new pull request for code merge

**Pull request closed without merging**
