### PR TITLE
Top 50 DBMS interview questions

### PR DESCRIPTION
**Pull request by thecoder8890**
@AkashSingh3031 : This is the **Top 50 DBMS interview questions**

### CODE REVIEW

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Can you add example and images if possible

**Comment by thecoder8890** [comment]
@AkashSingh3031 for this set I dont have any images, from next onwards will save images and include that.

**Comment by thecoder8890** [comment]
> Can you add example and images if possible
@AkashSingh3031 for this set I dont have any images, from next onwards will save images and include that.

**Comment by AkashSingh3031** [comment]
Ok
Try to add resources in a topic wise folder

**Review by AkashSingh3031 — COMMENTED** [review]
Accepted

But try to improve

**Pull request merged**
