### PR TITLE
 Added 17 programs using C++

### PR DESCRIPTION
**Pull request by RAUNAK-PANDEY**

### CODE REVIEW

**Review by AkashSingh3031 — CHANGES_REQUESTED** [review]
Please mention the number of question 
like: `_01)_First_and_Last_Position_of_an_Element.cpp` instead of `First and last occurrences of x.cpp`

**Comment by RAUNAK-PANDEY** [comment]
@AkashSingh3031 for all files right or only this one?

**Comment by RAUNAK-PANDEY** [comment]
@AkashSingh3031 I have mentioned the number in all questions. Please check.

**Review by AkashSingh3031 — COMMENTED** [review]
Accepted

**Pull request merged**
